###  List of packages to install. The following installation steps are just a guide and may go wrong!  Set your repository first.
library("devtools")
install.packages("tidyverse")
install.packages("rstan")
install.packages("phytools")
install.packages("digest")
install.packages("metafor")
install.packages("RColorBrewer")
install.packages("colorspace")
install.packages("pheatmap")
install.packages("yaml")
install.packages("broom")
install.packages("RVAideMemoire")
install.packages("DescTools")
install.packages("ggpubr")
install.packages("cloneRate")
install.packages("bookdown")
install.packages("ggtext")
install.packages("ggnewscale")
install.packages("ggh4x")
install.packages("optimx")
install.packages("lmeresampler")
install.packages("sjPlot")
install.packages("import")
install.packages("lme4")
install.packages("nlme")
install.packages("see")
install.packages("TeachingDemos")
install.packages("Hmisc")
install.packages("dfoptim")
if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("MutationalPatterns")
BiocManager::install("TxDb.Hsapiens.UCSC.hg19.knownGene")
BiocManager::install("BSgenome.Hsapiens.UCSC.hg38")
BiocManager::install("TxDb.Hsapiens.UCSC.hg38.knownGene")
devtools::install_github("kgori/sigfit", build_vignettes = TRUE,
                         build_opts = c("--no-resave-data", "--no-manual"))
#devtools::install_github("nangalialab/rsimpop")
#devtools::install_github("nangalialab/rtreefit",build_vignettes=TRUE)
## Install from the source files in this repo.
install.packages("rtreefit_1.1.0.tar.gz",repos=NULL,type="source") ## More recent than the public version.
install.packages("rsimpop_2.4.1.tar.gz",repos=NULL,type="source") 
devtools::install_git("https://github.com/nangalialab/treemut")
